/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class net_sf_jmsmq_MSMQQueue */

#ifndef _Included_net_sf_jmsmq_MSMQQueue
#define _Included_net_sf_jmsmq_MSMQQueue
#ifdef __cplusplus
extern "C" {
#endif
/* Inaccessible static: MQ_TIMEOUT */
/* Inaccessible static: MQ_SEND_AS_UNICODE */
#undef net_sf_jmsmq_MSMQQueue_serialVersionUID
#define net_sf_jmsmq_MSMQQueue_serialVersionUID 6594743192578354083i64
/*
 * Class:     net_sf_jmsmq_MSMQQueue
 * Method:    jniMQCloseHandle
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_net_sf_jmsmq_MSMQQueue_jniMQCloseHandle
  (JNIEnv *, jobject);

/*
 * Class:     net_sf_jmsmq_MSMQQueue
 * Method:    jniMQCloseCursorHandle
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_net_sf_jmsmq_MSMQQueue_jniMQCloseCursorHandle
  (JNIEnv *, jobject);

/*
 * Class:     net_sf_jmsmq_MSMQQueue
 * Method:    jniMQGetStringQueueProperty
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_net_sf_jmsmq_MSMQQueue_jniMQGetStringQueueProperty
  (JNIEnv *, jobject, jint);

/*
 * Class:     net_sf_jmsmq_MSMQQueue
 * Method:    jniMQGetIntQueueProperty
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_net_sf_jmsmq_MSMQQueue_jniMQGetIntQueueProperty
  (JNIEnv *, jobject, jint);

/*
 * Class:     net_sf_jmsmq_MSMQQueue
 * Method:    jniMQSetQueueProperty
 * Signature: (ILjava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_net_sf_jmsmq_MSMQQueue_jniMQSetQueueProperty
  (JNIEnv *, jobject, jint, jstring);

/*
 * Class:     net_sf_jmsmq_MSMQQueue
 * Method:    jniMQDeleteQueue
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_net_sf_jmsmq_MSMQQueue_jniMQDeleteQueue
  (JNIEnv *, jobject);

/*
 * Class:     net_sf_jmsmq_MSMQQueue
 * Method:    jniMQOpenQueue
 * Signature: (II)I
 */
JNIEXPORT jint JNICALL Java_net_sf_jmsmq_MSMQQueue_jniMQOpenQueue
  (JNIEnv *, jobject, jint, jint);

/*
 * Class:     net_sf_jmsmq_MSMQQueue
 * Method:    jniMQPurgeQueue
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_net_sf_jmsmq_MSMQQueue_jniMQPurgeQueue
  (JNIEnv *, jobject);

/*
 * Class:     net_sf_jmsmq_MSMQQueue
 * Method:    jniMQReadQueue
 * Signature: (IIJLnet/sf/jmsmq/MSMQMessage;)I
 */
JNIEXPORT jint JNICALL Java_net_sf_jmsmq_MSMQQueue_jniMQReadQueue
  (JNIEnv *, jobject, jint, jint, jlong, jobject);

/*
 * Class:     net_sf_jmsmq_MSMQQueue
 * Method:    jniMQSendQueue
 * Signature: (Lnet/sf/jmsmq/MSMQMessage;IZ)I
 */
JNIEXPORT jint JNICALL Java_net_sf_jmsmq_MSMQQueue_jniMQSendQueue
  (JNIEnv *, jobject, jobject, jint, jboolean);

#ifdef __cplusplus
}
#endif
#endif
